"""Digest rendering for email bodies."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from .models import Paper


@dataclass
class Digest:
    """Represents a generated digest ready for rendering."""

    items: list[Paper]
    window_start: datetime
    window_end: datetime
    interests: str
    summary: str = ""
    total_fetched: int = 0


def render_digest(digest: Digest) -> tuple[str, str]:
    """Render digest to plain text and HTML bodies.

    Args:
        digest: Digest object with papers and metadata

    Returns:
        Tuple of (text_body, html_body)
    """
    text_body = _render_text(digest)
    html_body = _render_html(digest)
    return text_body, html_body


def _render_text(digest: Digest) -> str:
    """Render digest as plain text."""
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("Daily Research Digest")
    lines.append("=" * 60)
    lines.append("")

    # Window info
    start_str = digest.window_start.strftime("%Y-%m-%d %H:%M %Z")
    end_str = digest.window_end.strftime("%Y-%m-%d %H:%M %Z")
    lines.append(f"Period: {start_str} to {end_str}")
    lines.append(f"Interests: {digest.interests}")
    lines.append("")

    if not digest.items:
        lines.append("No relevant papers found for this period.")
        lines.append("")
        return "\n".join(lines)

    # Summary
    lines.append(f"Found {len(digest.items)} relevant papers")
    if digest.total_fetched:
        lines.append(f"(from {digest.total_fetched} total papers)")
    lines.append("")
    lines.append("-" * 60)
    lines.append("")

    # Papers
    for i, paper in enumerate(digest.items, 1):
        lines.append(f"{i}. [{paper.relevance_score:.1f}/10] {paper.title}")
        lines.append(f"   Authors: {', '.join(paper.authors[:3])}")
        if len(paper.authors) > 3:
            lines[-1] += f" +{len(paper.authors) - 3} more"
        lines.append(f"   Link: {paper.link}")
        if paper.relevance_reason:
            lines.append(f"   Reason: {paper.relevance_reason}")
        lines.append("")

    # Footer
    lines.append("-" * 60)
    lines.append("Generated by Daily Research Digest")
    lines.append("https://github.com/LevRoz630/daily-research-digest")

    return "\n".join(lines)


def _render_paper_html(paper: Paper, index: int) -> str:
    """Render a single paper as HTML."""
    authors_str = ", ".join(paper.authors[:3])
    if len(paper.authors) > 3:
        authors_str += f" +{len(paper.authors) - 3} more"

    score_color = _score_color(paper.relevance_score)

    # Build reason HTML if present
    reason_html = ""
    if paper.relevance_reason:
        escaped_reason = _escape_html(paper.relevance_reason)
        reason_html = (
            f'<p style="margin: 0; color: #444; font-size: 13px;">' f"<em>{escaped_reason}</em></p>"
        )

    return f"""
    <div style="margin-bottom: 20px; padding: 15px; background: #f8f9fa;
                border-radius: 8px; border-left: 4px solid {score_color};">
        <div style="margin-bottom: 8px;">
            <span style="display: inline-block; padding: 2px 8px;
                        background: {score_color}; color: white;
                        border-radius: 4px; font-size: 12px; font-weight: bold;">
                {paper.relevance_score:.1f}/10
            </span>
        </div>
        <h3 style="margin: 0 0 8px 0; font-size: 16px;">
            <a href="{paper.link}" style="color: #1a0dab; text-decoration: none;">
                {index}. {_escape_html(paper.title)}
            </a>
        </h3>
        <p style="margin: 0 0 8px 0; color: #666; font-size: 14px;">
            {_escape_html(authors_str)}
        </p>
        {reason_html}
    </div>
    """


def _render_html(digest: Digest) -> str:
    """Render digest as HTML."""
    start_str = digest.window_start.strftime("%Y-%m-%d %H:%M %Z")
    end_str = digest.window_end.strftime("%Y-%m-%d %H:%M %Z")

    # Build papers HTML
    if not digest.items:
        papers_html = """
        <p style="color: #666; font-style: italic;">
            No relevant papers found for this period.
        </p>
        """
    else:
        papers_html = ""
        for i, paper in enumerate(digest.items, 1):
            papers_html += _render_paper_html(paper, i)

    # Build summary
    summary_html = ""
    if digest.total_fetched:
        count = len(digest.items)
        total = digest.total_fetched
        summary_html = (
            f"<p>Found <strong>{count}</strong> relevant papers " f"from {total} total.</p>"
        )
    elif digest.items:
        summary_html = f"<p>Found <strong>{len(digest.items)}</strong> relevant papers.</p>"

    interests_escaped = _escape_html(digest.interests)

    # Build body styles
    body_style = (
        "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, "
        "'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; "
        "max-width: 600px; margin: 0 auto; padding: 20px;"
    )

    # Build header styles
    header_style = (
        "background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); "
        "padding: 30px; border-radius: 12px; color: white; "
        "text-align: center; margin-bottom: 30px;"
    )

    # Build footer styles
    footer_style = (
        "margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; "
        "text-align: center; color: #999; font-size: 12px;"
    )

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="{body_style}">

    <div style="{header_style}">
        <h1 style="margin: 0 0 10px 0; font-size: 28px;">Daily Research Digest</h1>
        <p style="margin: 0; opacity: 0.9; font-size: 14px;">
            {start_str} to {end_str}
        </p>
    </div>

    <div style="margin-bottom: 25px; padding: 15px; background: #e8f4f8;
                border-radius: 8px;">
        <p style="margin: 0;">
            <strong>Interests:</strong> {interests_escaped}
        </p>
    </div>

    {summary_html}

    <div style="margin-top: 25px;">
        {papers_html}
    </div>

    <div style="{footer_style}">
        <p>Generated by
            <a href="https://github.com/LevRoz630/daily-research-digest"
               style="color: #667eea;">Daily Research Digest</a>
        </p>
    </div>

</body>
</html>"""

    return html


def _score_color(score: float) -> str:
    """Get color for relevance score."""
    if score >= 8:
        return "#28a745"  # Green - highly relevant
    elif score >= 6:
        return "#17a2b8"  # Blue - relevant
    elif score >= 4:
        return "#ffc107"  # Yellow - somewhat relevant
    else:
        return "#6c757d"  # Gray - low relevance


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
